name: Transfer-wdpe
author: RealBJsingh
main: real\Transfer\Transfer
version: 1.0.0
api: 4.0.0
load: STARTUP
description: "A Transfer command plugin for pocketmine 4.0 which works with waterdogpe."
commands:
  transfer:
    usage: /transfer <server>
    description: Transfer yourself to different server
permissions:
  wdpe.transfer.command:
    description: "Permission to use Transfer command"
    default: true